language: javascript

install:
  - 

cache:
  directories:
    - 

matrix:
  include:
    - env:
      - TASK=build
      script: uname -a

deploy:
  provider: script
  script: bash .deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false" && $TASK = "build"
