language: javascript

install:
  - 

cache:
  directories:
    - 

matrix:
  include:
    - env:
      - 
      script: 

deploy:
  provider: script
  script: bash .deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false"
